# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86d93ab5a53f46e578f1480fd1600a15af7eb3a233a79114ff0b292ca0ab1a705f919309e043807feb4ac595501bb737faa675a91d7af0d2fb18df741302cf76

test:
  secret_key_base: ad051aca631279f056551086129c3ba890c44f1539829564e890538d2e0741b6546313d0eb5130f1f8d6ab7e2ff0ddf92789a16cdd2deab433bdec68090fc505

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
